name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  CI:
    env:
      working-directory: ./kb-jobtrainning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        java --version
    - name: Build with Gradle
      run: |
        update-alternatives --list java
        java --version
        ./gradlew -version
        sudo ./gradlew clean build
    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: rkdals213/kb-jobtrainning
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PW }}
        
  deploy:
    needs: CI
    name: Deploy
    runs-on: [ self-hosted ]
    steps:
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Docker run
        run: |
          docker stop kb-jobtrainning && docker rm -fv kb-jobtrainning
          docker rmi -f rkdals213/kb-jobtrainning
          docker run -d -p 8080:8080 --name kb-jobtrainning --restart always rkdals213/kb-jobtrainning:latest
